# MeepleStats

volumes:
  db:
  data:

services:
  mongo:
    image: mongo:4.4
    container_name: meeplestats-mongo
    restart: unless-stopped
    volumes:
      - db:/data/db
    ports:
      - '27017:27017'
    env_file: ./.env

  backend:
    image: ghcr.io/tommythehuman/meeplestats/backend:latest
    container_name: meeplestats-backend
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - '5000:5000'
    env_file: ./.env
    depends_on:
      - mongo

  frontend:
    image: ghcr.io/tommythehuman/meeplestats/frontend:latest
    container_name: meeplestats-frontend
    ports:
      - '5173:5173'
    env_file: ./.env
    depends_on:
      - backend
