name: Create and publish a Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Build the Docker frontend image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: docker build -t ghcr.io/${{ env.IMAGE_NAME }}/frontend:latest frontend/meeplestats/Dockerfile

      - name: Build the Docker backend image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: docker build -t ghcr.io/${{ env.IMAGE_NAME }}/backend:latest backend/Dockerfile

      - name: Push the frontend image
        run: docker push ghcr.io/${{ env.IMAGE_NAME }}/frontend:latest

      - name: Push the backend image
        run: docker push ghcr.io/${{ env.IMAGE_NAME }}/backend:latest
